services:
  gruuk-server:
    image: ${IMAGE:-805149719934.dkr.ecr.us-east-2.amazonaws.com/gruuk-server:latest}
    restart: unless-stopped
    ports:
      - "8090:8080"
    env_file:
      - .env
    environment:
      DOMAIN: gk.kspt.dev
      LISTEN_ADDR: :8080
