FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /gruuk-server ./cmd/gruuk-server

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /gruuk-server /usr/local/bin/gruuk-server
EXPOSE 8080
ENTRYPOINT ["gruuk-server"]
